apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kube-jenkin
  name: kube-jenkin
spec:
  ports:
  - name: kube-jenkin
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: kube-jenkin
  type: NodePort
status:
  loadBalancer: {}
